# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('likes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Names'),
        ),
    ]
