# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='address',
        ),
        migrations.RemoveField(
            model_name='names',
            name='link',
        ),
        migrations.RemoveField(
            model_name='names',
            name='phone',
        ),
        migrations.AlterField(
            model_name='names',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
