# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_names_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='character',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='personality',
        ),
        migrations.AddField(
            model_name='character',
            name='namelink',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
