# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20161126_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='namelink',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
